/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/maps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Floor Plans */
        get: operations["list_floor_plans_api_v1_maps_get"];
        put?: never;
        /** Create Floor Plan */
        post: operations["create_floor_plan_api_v1_maps_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/maps/{map_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Floor Plan */
        get: operations["get_floor_plan_api_v1_maps__map_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/maps/{map_id}/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Zones */
        get: operations["list_zones_api_v1_maps__map_id__zones_get"];
        put?: never;
        /** Create Zone */
        post: operations["create_zone_api_v1_maps__map_id__zones_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/maps/{map_id}/aps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Aps */
        get: operations["list_aps_api_v1_maps__map_id__aps_get"];
        put?: never;
        /** Create Ap */
        post: operations["create_ap_api_v1_maps__map_id__aps_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccessPointCreate */
        AccessPointCreate: {
            /** Mac Address */
            mac_address: string;
            /** Name */
            name?: string | null;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** AccessPointResponse */
        AccessPointResponse: {
            /** Mac Address */
            mac_address: string;
            /** Name */
            name?: string | null;
            /** X */
            x: number;
            /** Y */
            y: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Floor Plan Id
             * Format: uuid
             */
            floor_plan_id: string;
        };
        /** FloorPlanCreate */
        FloorPlanCreate: {
            /** Name */
            name: string;
            /** Building */
            building: string;
            /** Floor */
            floor: string;
            /** Svg Url */
            svg_url?: string | null;
            /** Image Url */
            image_url?: string | null;
            /** Width */
            width: number;
            /** Height */
            height: number;
        };
        /** FloorPlanResponse */
        FloorPlanResponse: {
            /** Name */
            name: string;
            /** Building */
            building: string;
            /** Floor */
            floor: string;
            /** Svg Url */
            svg_url?: string | null;
            /** Image Url */
            image_url?: string | null;
            /** Width */
            width: number;
            /** Height */
            height: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Zones
             * @default []
             */
            zones: components["schemas"]["ZoneResponse"][];
            /**
             * Access Points
             * @default []
             */
            access_points: components["schemas"]["AccessPointResponse"][];
        };
        /** FloorPlanSummary */
        FloorPlanSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Building */
            building: string;
            /** Floor */
            floor: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ZoneCreate */
        ZoneCreate: {
            /** Name */
            name: string;
            /**
             * Zone Type
             * @default general
             */
            zone_type: string;
            /**
             * Polygon
             * @description Array of [x, y] coordinates
             */
            polygon: number[][];
        };
        /** ZoneResponse */
        ZoneResponse: {
            /** Name */
            name: string;
            /**
             * Zone Type
             * @default general
             */
            zone_type: string;
            /**
             * Polygon
             * @description Array of [x, y] coordinates
             */
            polygon: number[][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Floor Plan Id
             * Format: uuid
             */
            floor_plan_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_floor_plans_api_v1_maps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FloorPlanSummary"][];
                };
            };
        };
    };
    create_floor_plan_api_v1_maps_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FloorPlanCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FloorPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_floor_plan_api_v1_maps__map_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                map_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FloorPlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_zones_api_v1_maps__map_id__zones_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                map_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_zone_api_v1_maps__map_id__zones_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                map_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ZoneCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_aps_api_v1_maps__map_id__aps_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                map_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessPointResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_ap_api_v1_maps__map_id__aps_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                map_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccessPointCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessPointResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
