"""add assets table

Revision ID: 3d0c01f2b0a0
Revises: ea5c830cfaf5
Create Date: 2026-06-26 17:41:04.038705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d0c01f2b0a0'
down_revision: Union[str, Sequence[str], None] = 'ea5c830cfaf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('last_x', sa.Float(), nullable=True),
    sa.Column('last_y', sa.Float(), nullable=True),
    sa.Column('last_floor_id', sa.UUID(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_mac_address'), 'assets', ['mac_address'], unique=True)
    op.create_table('floor_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('width_m', sa.Float(), nullable=False),
    sa.Column('height_m', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('floor_plans')
    op.drop_index(op.f('ix_assets_mac_address'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
