"""add floor_plans table

Revision ID: ea5c830cfaf5
Revises: 2fb656d10a2c
Create Date: 2026-06-26 17:25:22.871565

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'ea5c830cfaf5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
