"""initial map schema

Revision ID: 432bc8e5b82d
Revises: 
Create Date: 2026-06-22 20:26:14.818720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '432bc8e5b82d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('floor_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('building', sa.String(), nullable=False),
    sa.Column('floor', sa.String(), nullable=False),
    sa.Column('svg_url', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('floor_plan_id', sa.UUID(), nullable=False),
    sa.Column('mac_address', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['floor_plan_id'], ['floor_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mac_address')
    )
    op.create_table('zones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('floor_plan_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('zone_type', sa.String(), nullable=True),
    sa.Column('polygon', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['floor_plan_id'], ['floor_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zones')
    op.drop_table('access_points')
    op.drop_table('floor_plans')
    # ### end Alembic commands ###
